# Modules Used

# https://docs.ansible.com/ansible/latest/modules/cloudformation_module.html
# https://docs.ansible.com/ansible/latest/modules/cloudformation_info_module.html
# https://docs.ansible.com/ansible/latest/user_guide/playbooks_delegation.html 
---

- name: "Deploy AWS VPC Environment"
  hosts: localhost
  gather_facts: False
  connection: local

# Launch AWS infrastruture cloudformation stack
  tasks:
    - name: Deploy AWS VPC Environment
      cloudformation:
        stack_name: ""
        state: present
        region: us-west-2
        disable_rollback: false
        template: "~/f5-rs-aws/templates/f5-network-only-2AZ-for-3nic-bigip.template"
        template_parameters:
          allowUsageAnalytics: "Yes"
          application: "f5app"
          availabilityZone1: "us-west-2a"
          availabilityZone2: "us-west-2b"
#         bigIpModules: "ltm:nominal"
          costcenter: "f5costcenter"
          customImageId: "OPTIONAL"
          declarationUrl: "none"
          environment: "f5env"
          group: "f5group"
          owner: "f5owner"
        tags:
          Stack: ansible-cloudformations

# Get summary information about a stack
      cloudformation_info:
        stack_name: ""
      register: "InfrastrutureCloudformationOutput"
      
# Output the stack information to ~/
    - local_action: 
        copy content={{ InfrastrutureCloudformationOutput }} dest=~/ansible-infrastruture-cloudformation-output.txt