# Modules Used

# https://docs.ansible.com/ansible/latest/modules/cloudformation_module.html
# https://docs.ansible.com/ansible/latest/modules/cloudformation_info_module.html
# https://docs.ansible.com/ansible/latest/user_guide/playbooks_delegation.html 
---

- name: "Deploy AWS BIGIP Cluster"
  hosts: localhost
  gather_facts: False
  connection: local

# Launch AWS bigip cloudformation stack
  tasks:
    - name: create a stack, pass in the template body via lookup template
      cloudformation:
        stack_name: ""
        state: present
        region: us-west-2
        disable_rollback: false
        template: "~/f5-rs-aws/templates/f5-existing-stack-same-az-cluster-bigiq-3nic-bigip.template"
        template_parameters:
          Vpc: ""
          managementSubnetAz1: ""
          subnet1Az1: ""
          subnet2Az1: ""
          imageName: "AllTwoBootLocations"
          customImageId: "OPTIONAL"
          instanceType: "m5.xlarge"
          sshKey: ""
          restrictedSrcAddress: ""
          restrictedSrcAddressApp: ""
          ntpServer: "0.pool.ntp.org"
          timezone: "UTC"
          bigIpModules: "ltm:nominal,asm:nominal"
          application: "f5app"
          environment: "f5env"
          group: "f5group"
          owner: "f5owner"
          costcenter: "f5costcenter"
          bigiqAddress: ""
          bigiqUsername: ""
          bigIqLicenseUnitOfMeasure: ""
          bigIqLicenseSkuKeyword1: ""
          bigiqPasswordS3ARN: ""
          bigiqLicensePoolName: ""
          allowUsageAnalytics: "f5owner"
          declarationUrl: "none"
          provisionPublicIP: "yes"
        tags:
          Stack: ansible-cloudformations
# Get summary information about a stack
      cloudformation_info:
        stack_name: ""
      register: "BigipCloudformationOutput"
# Output the stack information to ~/
    - local_action: 
        copy content={{ BigipCloudformationOutput }} dest=~/ansible-bigip-cloudformation-output.txt