---
# Modules Used

# https://docs.ansible.com/ansible/latest/modules/set_fact_module.html
# https://docs.ansible.com/ansible/latest/modules/bigip_wait_module.html
# https://docs.ansible.com/ansible/latest/modules/uri_module.html
# https://docs.ansible.com/ansible/latest/modules/template_module.html
# https://docs.ansible.com/ansible/latest/modules/get_url_module.html


# Ansible Information
- name: Set Ansible Information
  hosts: localhost
  gather_facts: False
  connection: local
  vars:
    BIGIPadminUsername: ""
    BIGIPadminPassword: ""
    deviceName1: ""
    serviceName: ""
    virtualAddresses: ""
    accessKeyId: ""
    secretAccessKey: ""
    tagKey: ""
    tagValue: ""

# Deploy 
  tasks:
    - name: Wait a maximum of 300 seconds for BIG-IP to be ready to take configuration
      bigip_wait:
        timeout: 300
        provider:
          password: "{{ BIGIPadminPassword }}"
          server: "{{ deviceName1 }}"
          user: "{{ BIGIPadminUsername }}"
          validate_certs: no

    - name: Get BIG-IP Authentication Token from {{ deviceName1 }}
      uri:
        body: '{"username":"{{ BIGIPadminUsername }}","password":"{{ BIGIPadminPassword }}","loginProviderName":"tmos"}'
        body_format: json
        method: POST
        url: "https://{{ deviceName1 }}/mgmt/shared/authn/login"
        status_code: "200"
        validate_certs: no
      register: bigip1_auth_response
      retries: 30
      delay: 5
      until: "(bigip1_auth_response is successful) and (bigip1_auth_response.status == 200)"

    - name: Assign Auth Token to Variable
      set_fact:
        bigip1_auth_token: "{{ bigip1_auth_response.json.token.token }}"

    - name: Prepare the AS3 declaration
      template: src="~/f5-rs-aws/templates/application-services-3.template" dest="~/f5-rs-aws/templates/{{ serviceName }}_declaration.j2"
      delegate_to: localhost

    - name: Validate {{ deviceName1 }} AS3 Rest Worker is ready
      uri:
        headers:
          X-F5-Auth-Token: "{{ bigip1_auth_token }}"
        method: GET
        url: "https://{{ deviceName1 }}/mgmt/shared/appsvcs/available"
        validate_certs: no
      retries: 30
      delay: 5
      register: result
      until: "(result is successful) and (result.status == 200)"

    - name: Create or update {{ serviceName }}; AS3 Declaration
      uri:
        body: "{{ lookup('file','~/f5-rs-aws/templates/' + '{{ serviceName }}_declaration.j2') }}"
        body_format: json
        headers:
          X-F5-Auth-Token: "{{ bigip1_auth_token }}"
        method: POST
        status_code: "200"
        url: "https://{{ deviceName1 }}/mgmt/shared/appsvcs/declare"
        validate_certs: no
        timeout: "60"

    - name: Delete BIG-IP Authentication Token from {{deviceName1}}
      uri:
        headers:
          X-F5-Auth-Token: "{{ bigip1_auth_token }}"
        method: DELETE
        url: "https://{{ deviceName1 }}/mgmt/shared/authz/tokens/{{ bigip1_auth_token }}"
        status_code: "200"
        validate_certs: no
      register: bigip1_token_delete
      retries: 30
      delay: 5
      until: "(bigip1_token_delete is successful) and (bigip1_token_delete.status == 200)"