---
# Modules Used

# https://docs.ansible.com/ansible/latest/modules/cloudformation_module.html
# https://docs.ansible.com/ansible/latest/modules/cloudformation_info_module.html
# https://docs.ansible.com/ansible/latest/user_guide/playbooks_delegation.html 

# Ansible Information
- name: Set Ansible Information
  hosts: localhost
  gather_facts: False
  connection: local
  vars:
    stack_name: ""
    #More variables below

# Destroy AWS BIGIP Cluster stack
  tasks:
    - name: Destroy AWS BIGIP cluster cloudformation stack
      cloudformation:
        stack_name: "{{ stack_name }}"
        state: absent

    - name: Get summary information about a stack
      cloudformation_info:
        stack_name: "{{ stack_name }}"
      register: "BigipCloudformationOutput"
      
    - name: Output the stack information to ~/
      local_action: 
        copy content={{ BigipCloudformationOutput }} dest=~/ansible-bigip-cloudformation-output.txt