# Modules Used

# https://docs.ansible.com/ansible/latest/modules/cloudformation_module.html
---

- name: "Deploy AWS VPC Environment"
  hosts: localhost
  gather_facts: False
  connection: local

# Destroy AWS infrastruture cloudformation stack
  tasks:
    - name: destroy a stack
      cloudformation:
        stack_name: ""
        state: absent
# Get summary information about a stack
      cloudformation_info:
        stack_name: ""
      register: "InfrastrutureCloudformationOutput"
# Output the stack information to ~/
    - local_action: 
        copy content={{ InfrastrutureCloudformationOutput }} dest=~/ansible-infrastruture-cloudformation-output.txt